services:
  - type: web
    name: django-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/manage.py runserver 0.0.0.0:8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

  - type: web
    name: fastapi-converter
    env: python
    rootDir: backend/converters
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free

  - type: web
    name: pseudocode-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
